name: ci
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Init (test context)
        working-directory: test/fixtures/simple
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint --init && tflint

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.6

      - name: Terraform tests
        run: terraform test
